### ISSUE TITLE
Missing commit edf196117233

### ISSUE THREAD

**Issue by MarekPasnikowski** [ProtonMail/go-crypto#261]
proton-bridge, go-proton-api and proton-mail-export require `github.com/ProtonMail/go-crypto v0.0.0-20230717121622-edf196117233`

This revision does not exist in this Github repository, which causes failures like https://github.com/ProtonMail/proton-bridge/issues/459 .

**Comment by twiss** [comment]
Hi :wave: Thanks for the report! Should be fixed now.

**Comment by MarekPasnikowski** [comment]
Thank you for quick solution. I confirm I am able to build the module now, though the Github search still does not return the commit object.

**Comment by Naftagaz21** [comment]
Hey @MarekPasnikowski the commit is visible, in fact it was in the past even though it was "detached".

Here ya go:
https://github.com/ProtonMail/go-crypto/commit/edf196117233
